### ISSUE TITLE
Discoverが動作しない。

### ISSUE THREAD

**Issue by Sylphid-Modder** [PlasmaLinux/issuetracker#2]
Discoverのインストールプロセスが完了しない。
エラーメッセージ:Too few items to install(だったはず)

パッケージ関係等を全て洗い出す必要があると思われる。

**Comment by Sylphid-Modder** [comment]
Discover: https://apps.kde.org/discover/

**Comment by rkarsnk** [comment]
Discoverをプリインストールするか，要検討

**Comment by Plasma-Linux** [comment]
Mac OSをネオン風にしてパクるためには必須だと思っている

**Comment by Sylphid-Modder** [comment]
Ubuntuソフトウェアセンターでは不十分?
どちらのUIもMac App Storeと似ているとは言えないし

**Comment by Plasma-Linux** [comment]
GNOME-Software?

**Comment by Plasma-Linux** [comment]
Gnome-Softwareでないのであれば検討する

**Comment by Sylphid-Modder** [comment]
はい。

**Comment by Plasma-Linux** [comment]
OK

**Comment by rkarsnk** [comment]
長年のLinuxユーザから言わせると，AppStoreのようなものは邪魔以外のなにものでもない．
DiscoverもGnome-softwareもUbuntuソフトウェアセンタも使い勝手のいいものではない．

**Comment by Plasma-Linux** [comment]
厳密に言えばUbuntu-SoftwareってのがUbuntuのデフォルトだったような気がする。(もしかしてUnity時代の時のみ?)

**Comment by rkarsnk** [comment]
Ubuntu-Software がUbuntuデフォルトとうので正しい．ただ使いにくくて邪魔…
aptの方が楽．

**Comment by rkarsnk** [comment]
この件，Discoverをインストールイメージに含めない方向で進めてはどうか．

**Comment by rkarsnk** [comment]
Ubuntu版の開発は中断のため，いったんクローズする．

**Comment by Sylphid-Modder** [comment]
このIssueはUbuntu版PlasmaLinuxの開発中断に基づき一時閉鎖されます。
また、Debian版PlasmaLinux(PLDE)には搭載の見込みはありません。
