### ISSUE TITLE
root権限を要求するGUIアプリケーションがショートカットから起動しない。

### ISSUE THREAD

**Issue by Sylphid-Modder** [PlasmaLinux/issuetracker#3]
原因不明。
設定項目等を全て見直す必要があると見込まれる。

例: lightdmの設定、pacup

**Comment by rkarsnk** [comment]
詳細が分からない．
- sudo が実行できない?
- 他に権限昇格する何かが上手く動いてない?
- GUIからroot権限を必要とするアプリが正常に動く場合，どういう動きをするのか?

**Comment by Plasma-Linux** [comment]
OK。Pinguybuilder側の問題もあると思われます。しかし、以前os-relaseを変更したらなぜか知りませんが変な挙動したのですよね。それが原因かもしれないので調査します。

**Comment by Sylphid-Modder** [comment]
このIssueはUbuntu版PlasmaLinuxの開発中断に伴い一時閉鎖されます。
