### ISSUE TITLE
サスペンド状態から戻ってこない

### ISSUE THREAD

**Issue by ghost** [PlasmaLinux/issuetracker#5]
サスペンドから戻ったあとずっと黒い画面のままです。
おそらく、xfceに問題がある可能性がある。

**Comment by rkarsnk** [comment]
@pabu1san サスペンドから復帰した状態で，`Ctrl+Alt+F1`や`Ctrl+Alt+F2`を押しても，ttyコンソールに切り替わらない?

**Comment by Plasma-Linux** [comment]
もしかしてxfce 4.18に強引に更新したのが原因かもです。Ubuntu 22.04はデフォルトでxfce 4.16が使われているので。

**Comment by Plasma-Linux** [comment]
最新技術か安定性か。とても重要ですね

**Comment by ghost** [comment]
これ確か昨日テストで作ったやつだけど、実際ガルダで起きたから、気を使ったほうがいいかもしれない

**Comment by rkarsnk** [comment]
安定性やね．Ubuntu標準のパッケージを使う方が安全
最新版を使ってゼロデイバグとか含まれてたら，対処しようがない．

あとLTS版以外からパッケージ持ってくる場合も，ライブラリの依存関係問題起きると対処しきれないから，やめた方がいい．

**Comment by Plasma-Linux** [comment]
なるほど。一応、XubuntuのPPAでその他のxfceのライブラリを拾ってるけどそれでもダメかー
