### ISSUE TITLE
Webページの更新

### ISSUE THREAD

**Issue by rkarsnk** [PlasmaLinux/issuetracker#9]
### SNSのリンクの追加
- Twitter
  - @PlasmaLinux_JP
- Discord 
  - https://discord.gg/dCkfHNe7n9
- [済] GitHub
 
### Welcome to Plasma Linux! 
- この文言必要ですか?

### 再構築してる旨の文章の変更
- どういう内容に変更するのか?要望ある?

**Comment by Plasma-Linux** [comment]
あーでもどうだろう。Welcome to PlasmaLinuxはなしにしようかな。
あと再構築に関しては、
「Plasma Linux のRebootに向けて，公式サイト準備中です．」を削除して「PlasmaLinuxへようこそ。このサイトはまだ未完成です」に変更できたらしてほしい。

**Comment by rkarsnk** [comment]
SNSリンクの追加は，今夜PullReq出します．

文章の変更は，あとでDiscordで内容共有します．

**Comment by Plasma-Linux** [comment]
了解です

**Comment by rkarsnk** [comment]
SNSリンク追加のPullRequesut出したので，確認してマージしてください．
https://github.com/PlasmaLinux/plasmalinux.github.io/pull/2

**Comment by rkarsnk** [comment]
記事の内容変更のPullReqを出したので，確認してください．
PullReq: https://github.com/PlasmaLinux/plasmalinux.github.io/pull/3

**Comment by rkarsnk** [comment]
反映したので，クローズ.
